import { createElement } from '@lwc/engine-dom';
import Cp_c_inputbox from 'c/cp_c_inputbox';

describe('c-cp-c-inputbox', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-cp-c-inputbox', {
            is: Cp_c_inputbox
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});