import { createElement } from '@lwc/engine-dom';
import Task1_studentRegistrationForm from 'c/task1_studentRegistrationForm';

describe('c-task1-student-registration-form', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-task1-student-registration-form', {
            is: Task1_studentRegistrationForm
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});